### ISSUE TITLE
[Bug] Dimension mismatch when using crates/llm/examples/embeddings.rs

### ISSUE THREAD

**Issue by Jeadie** [rustformers/llm#288]
I'm attempting to run the basic embedding example [embeddings.rs](https://github.com/rustformers/llm/blob/main/crates/llm/examples/embeddings.rs). I am getting the following error (RUST_BACKTRACE=1).
```shell
Loaded hyperparameters
ggml ctx size = 3567.88 MB

Loaded tensor 8/194
Loaded tensor 16/194
Loaded tensor 24/194
Loaded tensor 32/194
Loaded tensor 40/194
Loaded tensor 48/194
Loaded tensor 56/194
Loaded tensor 64/194
Loaded tensor 72/194
Loaded tensor 80/194
Loaded tensor 88/194
Loaded tensor 96/194
Loaded tensor 104/194
Loaded tensor 112/194
Loaded tensor 120/194
Loaded tensor 128/194
Loaded tensor 136/194
Loaded tensor 144/194
Loaded tensor 152/194
Loaded tensor 160/194
Loaded tensor 168/194
Loaded tensor 176/194
Loaded tensor 184/194
Loaded tensor 192/194
Loading of model complete
Model size = 3568.33 MB / num tensors = 194

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `7`,
 right: `28672`', /Users/jeadie/.cargo/git/checkouts/llm-d8a8bbe144aa0546/b3c9851/crates/llm-base/src/model/common.rs:88:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:211:5
   4: llm_base::model::common::extract_embeddings
             at /Users/jeadie/.cargo/git/checkouts/llm-d8a8bbe144aa0546/b3c9851/crates/llm-base/src/model/common.rs:88:9
   5: <llm_mpt::Mpt as llm_base::model::KnownModel>::evaluate
             at /Users/jeadie/.cargo/git/checkouts/llm-d8a8bbe144aa0546/b3c9851/crates/models/mpt/src/lib.rs:266:9
   6: <M as llm_base::model::Model>::evaluate
             at /Users/jeadie/.cargo/git/checkouts/llm-d8a8bbe144aa0546/b3c9851/crates/llm-base/src/model/mod.rs:131:9
   7: infima::get_embeddings
             at ./src/embed.rs:132:5
```

I have used the following models
- [bloom-560m-f16.bin](https://huggingface.co/rustformers/bloom-ggml/blob/main/bloom-560m-f16.bin)
- [mpt-7b-q4_0.bin](https://huggingface.co/rustformers/mpt-7b-ggml/blob/main/mpt-7b-q4_0.bin)
- [bloom-560m-q5_1-ggjt.bin](https://huggingface.co/rustformers/bloom-ggml/blob/main/bloom-560m-q5_1-ggjt.bin)

For example, `cargo run mpt mpt-7b-q4_0.bin`

The relevant part of my Cargo.toml
```toml
[dependencies]
llm = { git = "https://github.com/rustformers/llm" , branch = "main" }
llm-base = { git = "https://github.com/rustformers/llm" , branch = "main" }
```

Is there any examples/tutorials for using rustformers/llm just to create embeddings?

**Comment by Jeadie** [comment]
Can confirm that `cargo run --release mpt mpt-7b-q4_0.bin` raises the same error

**Comment by Jeadie** [comment]
The assertion is actually raised in rustformers, not ggml [[ref](https://github.com/rustformers/llm/blob/main/crates/llm-base/src/model/common.rs#L88)].

**Comment by Jeadie** [comment]
When i comment out the assertion in my .cargo packages, and rerun, i get a successful result
```
Model size = 588.75 MB / num tensors = 294
My favourite animal is the dog
  Embeddings length: 1024
  Embeddings first 10: Some([-0.00, -0.01, 0.01, 0.01, -0.00, -0.02, 0.00, -0.00, -0.00, 0.00])
---
My favourite animal is the dog
  Embeddings length: 1024
  Embeddings first 10: Some([-0.00, -0.01, 0.01, 0.01, -0.00, -0.02, 0.00, -0.00, -0.00, 0.00])
I have just adopted a cute dog
  Embeddings length: 1024
  Embeddings first 10: Some([0.01, 0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.01, 0.02, -0.02])
My favourite animal is the cat
  Embeddings length: 1024
  Embeddings first 10: Some([-0.00, -0.01, 0.01, 0.01, -0.00, -0.02, 0.00, -0.00, -0.00, 0.00])
---
Similarities:
  My favourite animal is the dog: 0.99999994
  I have just adopted a cute dog: 0.7189488
  My favourite animal is the cat: 0.67703915
  ```

**Comment by skirodev** [comment]
I'm sorry, previously I only submitted the code to fix the embeddings extraction for the LLaMA model. Perhaps you can try again later.

**Comment by Jeadie** [comment]
Thank you. When the attached PR gets merged I will retest and close upon success.

**Comment by philpax** [comment]
Have you had a chance to retest?

**Comment by Jeadie** [comment]
Confirmed that on `llm = { git = "https://github.com/rustformers/llm" , branch = "main" }` issue is not present. Closing. Thanks for the fix
