### ISSUE TITLE
failed to load LLaMA model

### ISSUE THREAD

**Issue by dr-kristau** [rustformers/llm#289]
The issue is basically:

```bash
$ RUST_BACKTRACE=full cargo run --release --example inference llama ggml-gpt4all-j-v1.3-groovy.bin
    Finished release [optimized] target(s) in 0.57s
     Running `target/release/examples/inference llama ggml-gpt4all-j-v1.3-groovy.bin`
Loaded hyperparameters
thread 'main' panicked at 'Failed to load LLaMA model from "ggml-gpt4all-j-v1.3-groovy.bin": non-specific I/O error', crates/llm/examples/inference.rs:49:9
stack backtrace:
   0:     0x562d564540da - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562d564540da - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562d564540da - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x562d564540da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562d5647a78e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x562d56450675 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x562d56453ea5 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x562d56453ea5 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x562d5645565f - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x562d5645539b - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x562d56455c08 - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:     0x562d56455b09 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:     0x562d56454546 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x562d56455812 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:     0x562d55fa5573 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:     0x562d55fb523a - inference::main::h8d12828009f5dc63
  16:     0x562d55fd1c53 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6ff1415e88b56abc
  17:     0x562d55fb6fe9 - std::rt::lang_start::{{closure}}::h9c14cc7e6ecd1e47
  18:     0x562d56449c7c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd6efcd3bec896f2c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
  19:     0x562d56449c7c - std::panicking::try::do_call::hce04e543bb1f4cbb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  20:     0x562d56449c7c - std::panicking::try::h3342dd4e1f680968
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  21:     0x562d56449c7c - std::panic::catch_unwind::h148ce1e59ac0cee7
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  22:     0x562d56449c7c - std::rt::lang_start_internal::{{closure}}::h25f9dda2057a67fe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
  23:     0x562d56449c7c - std::panicking::try::do_call::h7caaaeaf9401650b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  24:     0x562d56449c7c - std::panicking::try::he7d15285746cbbc2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  25:     0x562d56449c7c - std::panic::catch_unwind::h89fb4f50c0301fe0
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  26:     0x562d56449c7c - std::rt::lang_start_internal::h078acd489417d3c1
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  27:     0x562d55fb6a05 - main
  28:     0x7fe0d9e49b4a - __libc_start_call_main
  29:     0x7fe0d9e49c0b - __libc_start_main@@GLIBC_2.34
  30:     0x562d55fa5bb5 - _start
  31:                0x0 - <unknown>
```

I'm not sure where to start looking to resolve this error.

**Comment by LLukas22** [comment]
I think `ggml-gpt4all-j-v1.3-groovy` is not a LLaMA based model, it should be GPT-J based try to run it via:

`cargo run --release --example inference gptj ggml-gpt4all-j-v1.3-groovy.bin`

But if that's the original model from the GPT4ALL website it may not work as they recently diverted form the GGML format.
Maybe take a look at this: https://huggingface.co/rustformers/gpt4all-j-ggml 
Its the same model, but fully GGML compliant.

**Comment by dr-kristau** [comment]
Thank you for your quick response! I am following the [Usage instructions](https://github.com/rustformers/llm#usage) of the README.

Subbing in `gptj` gives me:

```bash
$ RUST_BACKTRACE=full cargo run --release --example inference gptj ggml-gpt4all-j-v1.3-groovy.bin
    Finished release [optimized] target(s) in 0.53s
     Running `target/release/examples/inference gptj ggml-gpt4all-j-v1.3-groovy.bin`
Loaded hyperparameters
thread 'main' panicked at 'Failed to load GPT-J model from "ggml-gpt4all-j-v1.3-groovy.bin": invariant broken: 999255479 <= 2 in Some("ggml-gpt4all-j-v1.3-groovy.bin")', crates/llm/examples/inference.rs:49:9
stack backtrace:
```
> Its the same model, but fully GGML compliant.

Running this:
```bash
$ RUST_BACKTRACE=full cargo run --release -- gptj infer -m gpt4all-j-q4_0.bin  -p "Tell me how cool the Rust
programming language is:"
```
works as expected. Thank you very much for your help.

**Comment by LLukas22** [comment]
Sorry for the confusion, i'll update the README later. I also don't like that the other Gpt4All models are incompatible, but there is nothing we can do to solve this. This hopefully will get resolved when we have a new stable model format, discussion are still ongoing here: https://github.com/ggerganov/ggml/issues/220

**Comment by danforbes** [comment]
Sorry that error was introduced by me. I have fixed it (I hope) here https://github.com/rustformers/llm/pull/290
